from typing import Protocol
from ..contracts.asset_library import BrainAssetView


class AssetLibraryPort(Protocol):
    def resolve(self, metadata_ref: str) -> BrainAssetView: ...
    def find_by_name(self, semantic_name: str) -> list[BrainAssetView]: ...
    def find_by_category(self, category: str) -> list[BrainAssetView]: ...
